version: '3'
services:
    redis:
        image: redis
        volumes:
        - redis_volume:/data
        ports:
        - 6379:6379
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: Franklin5
        volumes:
        - "./mysqldir/:/docker-entrypoint-initdb.d"
        - mysql_volume:/var/lib/mysql
        ports:
        - 3306:3306
    apache:
        build: apachedir
        volumes:
        - "./content:/var/www/html"
        ports:
        - 8080:80
    nginx:
        build: nginxdir
        volumes:
        - "./content:/usr/share/nginx/html"
        ports:
        - 80:80
        environment:
        - NGINX_PORT=80
        depends_on:
        - apache
volumes:
    mysql_volume:
    redis_volume: